// Per-dungeon ENEMY FACTS — the MDT-derived backbone for pull labeling / after-action. Generated by
// @wow/data scripts/import-mdt.mjs (generated/dungeon-enemies.json) and carried in the mechanics
// bundle. Maps an npcId to its MDT name, enemy-forces `count` (0 for bosses + their adds + non-counting
// trash), `encounterID` (boss-area marker), and the pack `groups` (clone `g`) it appears in.
//
// The segmenter detects pull BOUNDARIES from the combat log alone (player↔enemy damage gaps); these
// facts only ENRICH a detected pull (name it, weight enemy-forces %, flag combined/boss-area pulls).

export interface EnemyFact {
  /** MDT display name. */
  name: string;
  /** Enemy-forces value per mob — 0 for bosses, their adds, and non-counting trash. */
  count: number;
  /** Present when the npc belongs to a boss encounter (e.g. construct adds) — marks a boss-area pull. */
  encounterID?: number;
  /** MDT pack ids (clone `g`) this npc appears in — used to flag a pull that spans multiple packs. */
  groups: number[];
}

export interface DungeonEnemies {
  /** Enemy-forces total needed to complete the dungeon (the % denominator). */
  totalCount: number;
  enemies: Record<string, EnemyFact>;
}

/** dungeon englishName → enemy facts, as shipped in the mechanics bundle (`bundle.enemies`). */
export type EnemyFactsByDungeon = Record<string, DungeonEnemies>;

const normName = (s: string): string => s.toLowerCase().replace(/[^a-z0-9]/g, '');

/**
 * Resolve a run's dungeon (from CHALLENGE_MODE_START `dungeonName`) to its MDT enemy facts, tolerant
 * of punctuation/spacing differences ("Algeth'ar Academy" ⇄ the MDT englishName). Undefined when the
 * dungeon isn't in the bundle (older data, or a dungeon we haven't imported).
 */
export function dungeonEnemiesFor(
  db: EnemyFactsByDungeon | undefined,
  dungeonName: string | undefined,
): DungeonEnemies | undefined {
  if (!db || !dungeonName) return undefined;
  if (db[dungeonName]) return db[dungeonName];
  const norm = normName(dungeonName);
  for (const [k, v] of Object.entries(db)) if (normName(k) === norm) return v;
  return undefined;
}
