// Mechanics bundle — the single serialized artifact that fully provisions a SpellTable.
// It is what the backend serves (GET /mechanics) and the client fetches once per session (~28KB
// gzipped). The whole combat log stays on the client; only this small rulebook crosses the wire.
// Generated by @wow/data scripts/build-mechanics.mjs into generated/mechanics.json.

import {
  SpellTable,
  type SpellSeed,
  type SpellOverlay,
  type RemovalCategoryDef,
  type RemoverEntry,
  type DebuffsByDungeon,
  type SpellFact,
} from './spellTable.js';
import type { EnemyFactsByDungeon } from '../segments/enemyFacts.js';

export interface MechanicsBundle {
  /** Content hash for ETag / cache-busting. */
  version: string;
  generatedAt: string;
  seed: SpellSeed;
  overlay: SpellOverlay;
  categories: RemovalCategoryDef[];
  removers: Record<string, RemoverEntry>;
  debuffs: DebuffsByDungeon;
  facts: Record<string, SpellFact>;
  /** Per-dungeon enemy facts for pull labeling / after-action (optional for back-compat). */
  enemies?: EnemyFactsByDungeon;
}

/** Build the unified SpellTable from a bundle (seed + overlay + removal model + DB2 facts). */
export function tableFromBundle(b: MechanicsBundle): SpellTable {
  return SpellTable.fromData(
    b.seed,
    b.overlay,
    { categories: b.categories, removers: b.removers, debuffs: b.debuffs },
    { facts: b.facts },
  );
}

export interface MechanicsSource {
  /** When set, fetch the bundle from here (the backend mechanics endpoint). */
  url?: string;
  /** Bundled-at-build snapshot used offline or when the fetch fails. */
  fallback: MechanicsBundle;
}

/**
 * Resolve the mechanics bundle: fetch from `url` when configured, otherwise (or on any failure)
 * use the bundled `fallback`. This is the swappable seam — today the worker passes only `fallback`
 * (build-time JSON); pointing `url` at the backend makes the table live without a client redeploy.
 */
export async function loadMechanics(source: MechanicsSource): Promise<MechanicsBundle> {
  if (source.url) {
    try {
      const res = await fetch(source.url);
      if (res.ok) return (await res.json()) as MechanicsBundle;
    } catch {
      /* network/parse failure — fall back to the bundled snapshot */
    }
  }
  return source.fallback;
}
