// Mechanics bundle — the single serialized artifact that fully provisions a SpellTable.
// It is what the backend serves (GET /mechanics) and the client fetches once per session (~28KB
// gzipped). The whole combat log stays on the client; only this small rulebook crosses the wire.
// Generated by @wow/data scripts/build-mechanics.mjs into generated/mechanics.json.

import {
  SpellTable,
  type SpellSeed,
  type SpellOverlay,
  type RemovalCategoryDef,
  type RemoverEntry,
  type DebuffsByDungeon,
  type SpellFact,
} from './spellTable.js';
import type { EnemyFactsByDungeon } from '../segments/enemyFacts.js';
import type { Priority, RemovalCategory } from './spellTable.js';

/** Role-lensed advice for handling a mechanic. Missing roles simply don't render. */
export interface MechanicAdvice {
  generic?: string;
  tank?: string;
  healer?: string;
  dps?: string;
}

/** A video reference for the in-app learning card. */
export interface MechanicVideo {
  title?: string;
  url: string;
  /** Deep-link offset into the video, in seconds. */
  atSeconds?: number;
  /** Provenance hint, e.g. 'youtube'. */
  source?: string;
}

/**
 * A consolidated "mechanic card" — the single contributor-facing record for one enemy mechanic.
 * It unifies what used to be split across avoidable.json / debuffs.json / mechanic-advice.json:
 * identity, classification (which drives analytics via the build-derived overlay/debuffs), and the
 * learning content (summary / advice / videos) shown on the in-app card. Curated per dungeon (M+) or
 * per encounter (raid) under packages/data/curation/mechanics/; the build script fans the
 * classification back into bundle.overlay/bundle.debuffs and ships the whole card here in bundle.cards.
 */
export interface MechanicCard {
  spellId: number;
  /** Display name (DB2 facts also supply this; the card value wins for display). */
  name?: string;
  /** NPC source — boss or trash mob. */
  caster?: string;
  boss?: boolean;
  /** Display context: the dungeon name (M+) or encounter/instance (raid). */
  dungeon?: string;
  /** Raid only: the instance this encounter belongs to. */
  instance?: string;
  /** 'dungeon' | 'encounter' — the kind of curation context this card came from. */
  kind?: 'dungeon' | 'encounter';
  // --- classification (fanned into overlay/debuffs at build time) ---
  avoidable?: boolean;
  interruptPriority?: Priority;
  dispelPriority?: Priority;
  /** Present ⇒ this is a dangerous DEBUFF at the given level (registers dangerous-debuff membership). */
  danger?: 'dangerous' | 'regular';
  /** Optional removable-category override (DB2 supplies most); UNIONed into removableBy. */
  removableBy?: RemovalCategory[];
  /** Build-stamped DISPLAY field: the RESOLVED removable categories (DB2 facts ∪ override). Read-only —
   *  set by build:mechanics for dangerous-debuff cards so the in-app card can show "removable by …"
   *  without the runtime SpellTable. Do not hand-edit; use `removableBy` to override. */
  removableCategories?: RemovalCategory[];
  // --- learning content (the card) ---
  /** Short "what it does" blurb. */
  summary?: string;
  advice?: MechanicAdvice;
  videos?: MechanicVideo[];
  tags?: string[];
  confidence?: 'high' | 'medium' | 'low';
  /** Contributor credit shown in the in-app learning card ("Contributed by …"). */
  source?: string;
  /** Optional http(s) link for the contributor (guild/site/channel), rendered on `source`. */
  sourceUrl?: string;
  notes?: string;
}

/** Source-file provenance for generated mechanic cards. This lets the backend export the live/admin-
 *  approved mechanics library back into repo-shaped curation files without guessing paths or metadata. */
export interface MechanicCardSource {
  /** Path relative to packages/data/curation/mechanics, using forward slashes. */
  path: string;
  meta: {
    kind: 'dungeon' | 'encounter';
    name: string;
    slug: string;
    instance?: string;
    encounterId?: number;
  };
  spellIds: number[];
}

export interface MechanicsBundle {
  /** Content hash for ETag / cache-busting. */
  version: string;
  generatedAt: string;
  seed: SpellSeed;
  overlay: SpellOverlay;
  categories: RemovalCategoryDef[];
  removers: Record<string, RemoverEntry>;
  debuffs: DebuffsByDungeon;
  facts: Record<string, SpellFact>;
  /** Per-dungeon enemy facts for pull labeling / after-action (optional for back-compat). */
  enemies?: EnemyFactsByDungeon;
  /** Consolidated mechanic cards keyed by spellId (learning content + identity). Optional for back-compat. */
  cards?: Record<string, MechanicCard>;
  /** Repo source-file provenance for cards. Optional for older generated bundles. */
  cardSources?: MechanicCardSource[];
}

/** Build the unified SpellTable from a bundle (seed + overlay + removal model + DB2 facts). */
export function tableFromBundle(b: MechanicsBundle): SpellTable {
  return SpellTable.fromData(
    b.seed,
    b.overlay,
    { categories: b.categories, removers: b.removers, debuffs: b.debuffs },
    { facts: b.facts },
  );
}

export interface MechanicsSource {
  /** When set, fetch the bundle from here (the backend mechanics endpoint). */
  url?: string;
  /** Bundled-at-build snapshot used offline or when the fetch fails. */
  fallback: MechanicsBundle;
}

/**
 * Resolve the mechanics bundle: fetch from `url` when configured, otherwise (or on any failure)
 * use the bundled `fallback`. This is the swappable seam — today the worker passes only `fallback`
 * (build-time JSON); pointing `url` at the backend makes the table live without a client redeploy.
 */
export async function loadMechanics(source: MechanicsSource): Promise<MechanicsBundle> {
  if (source.url) {
    try {
      const res = await fetch(source.url);
      if (res.ok) return (await res.json()) as MechanicsBundle;
    } catch {
      /* network/parse failure — fall back to the bundled snapshot */
    }
  }
  return source.fallback;
}
